/**
 * Controlled skill vocabulary for CSV seed data.
 * Every talent profile skill and job requirement must use these exact names.
 */

export const SKILL_CATEGORIES = [
  'NLP/RAG',
  'AI Agent/Framework',
  'Data Analysis/ML',
  'Computer Vision',
  'Prompt Engineering',
  'Fine-tuning/Training',
  'Full-stack+AI',
] as const;

export type SkillCategory = (typeof SKILL_CATEGORIES)[number];

export const SKILL_VOCABULARY: Record<SkillCategory, string[]> = {
  'NLP/RAG': [
    'LangChain',
    'LlamaIndex',
    'RAG Pipeline',
    'Vector Database',
    'Pinecone',
    'Weaviate',
    'ChromaDB',
    'Milvus',
    'Text Embedding',
    'Semantic Search',
    'Document Parsing',
    'Chunking Strategy',
    'Prompt Chaining',
    'Retrieval Optimization',
    'Knowledge Graph',
    'NLP Preprocessing',
    'Named Entity Recognition',
    'Text Classification',
    'Sentiment Analysis',
    'Summarization',
  ],
  'AI Agent/Framework': [
    'AutoGPT',
    'CrewAI',
    'AutoGen',
    'LangGraph',
    'Tool Calling',
    'Function Calling',
    'Agent Orchestration',
    'Multi-Agent Systems',
    'ReAct Pattern',
    'Chain-of-Thought',
    'Planning Algorithms',
    'MCP Protocol',
    'Agent Memory',
    'Task Decomposition',
  ],
  'Data Analysis/ML': [
    'Python',
    'PyTorch',
    'TensorFlow',
    'Scikit-learn',
    'Pandas',
    'NumPy',
    'Data Visualization',
    'Feature Engineering',
    'Model Evaluation',
    'A/B Testing',
    'Statistical Modeling',
    'Time Series Analysis',
    'Recommendation Systems',
    'Anomaly Detection',
  ],
  'Computer Vision': [
    'OpenCV',
    'YOLO',
    'Image Segmentation',
    'Object Detection',
    'Image Classification',
    'OCR',
    'Stable Diffusion',
    'Midjourney Prompt',
    'GANs',
    'ControlNet',
    'Image Generation',
    'Video Analysis',
  ],
  'Prompt Engineering': [
    'System Prompt Design',
    'Few-Shot Prompting',
    'Chain-of-Thought Prompting',
    'Prompt Optimization',
    'Structured Output',
    'Guardrails',
    'Prompt Testing',
    'Red Teaming',
    'Evaluation Framework',
    'Instruction Tuning Design',
  ],
  'Fine-tuning/Training': [
    'LoRA',
    'QLoRA',
    'PEFT',
    'RLHF',
    'DPO',
    'SFT',
    'Dataset Curation',
    'Training Pipeline',
    'Model Compression',
    'Quantization',
    'Knowledge Distillation',
    'Distributed Training',
    'DeepSpeed',
    'vLLM',
  ],
  'Full-stack+AI': [
    'Next.js',
    'React',
    'TypeScript',
    'Node.js',
    'PostgreSQL',
    'Redis',
    'Vercel AI SDK',
    'OpenAI API',
    'Anthropic API',
    'Streaming UI',
    'WebSocket',
    'Docker',
    'Kubernetes',
    'CI/CD',
  ],
};

export const ALL_SKILLS: string[] = Object.values(SKILL_VOCABULARY).flat();

const SKILL_SET = new Set(ALL_SKILLS);

export function isValidSkillName(name: string): boolean {
  return SKILL_SET.has(name);
}

export function getSkillsByCategory(category: SkillCategory): string[] {
  return SKILL_VOCABULARY[category] ?? [];
}

export function getCategoryForSkill(name: string): SkillCategory | null {
  for (const [category, skills] of Object.entries(SKILL_VOCABULARY)) {
    if (skills.includes(name)) {
      return category as SkillCategory;
    }
  }

  return null;
}

export const CHINESE_FAMILY_NAMES = [
  '张',
  '王',
  '李',
  '赵',
  '刘',
  '陈',
  '杨',
  '黄',
  '周',
  '吴',
  '徐',
  '孙',
  '马',
  '胡',
  '朱',
  '郭',
  '何',
  '林',
  '罗',
  '高',
  '梁',
  '宋',
  '唐',
  '许',
  '邓',
  '冯',
  '韩',
  '曹',
  '彭',
  '萧',
  '蔡',
  '潘',
  '田',
  '董',
  '袁',
  '于',
  '余',
  '叶',
  '蒋',
  '杜',
  '苏',
  '魏',
  '程',
  '吕',
  '丁',
  '沈',
  '任',
  '姚',
  '卢',
  '傅',
  '钟',
  '姜',
  '崔',
  '谭',
  '廖',
  '范',
  '汪',
  '陆',
  '金',
  '石',
] as const;

export const CHINESE_GIVEN_NAMES = [
  '伟',
  '芳',
  '娜',
  '秀英',
  '敏',
  '静',
  '丽',
  '强',
  '磊',
  '洋',
  '勇',
  '艳',
  '杰',
  '娟',
  '涛',
  '明',
  '超',
  '秀兰',
  '霞',
  '平',
  '刚',
  '桂英',
  '文',
  '云',
  '建华',
  '玉兰',
  '建国',
  '淑珍',
  '志强',
  '秀珍',
  '思远',
  '子涵',
  '梓萱',
  '浩然',
  '欣怡',
  '宇轩',
  '雨桐',
  '博文',
  '诗涵',
  '俊杰',
  '天翔',
  '晓萌',
  '嘉琪',
  '子墨',
  '一诺',
  '梦琪',
  '皓轩',
  '诗雨',
  '子豪',
  '若溪',
  '致远',
  '语嫣',
  '昊天',
  '思琪',
  '鑫磊',
  '雅琴',
  '睿哲',
  '紫萱',
  '旭东',
  '雨菲',
] as const;

export const COMPANY_NAMES = [
  '星辰智能科技',
  '深蓝数据',
  '量子跃迁科技',
  '灵犀AI',
  '鲲鹏云智',
  '银河算力',
  '玄武安全',
  '凤凰智联',
  '麒麟大模型',
  '青龙机器人',
  '白泽研究院',
  '朝云科技',
  '九章智算',
  '墨子AI',
  '仓颉科技',
  '神农智慧',
  '华清智能',
  '中关村智谷',
  '西湖数智',
  '松山湖AI',
] as const;

export const SENIORITY_LEVELS = ['junior', 'mid', 'senior', 'lead'] as const;

export type SeniorityLevel = (typeof SENIORITY_LEVELS)[number];

export const BACKGROUND_TYPES = [
  'industry_engineer',
  'researcher_phd',
  'freelancer',
  'career_changer',
  'student',
  'startup_founder',
] as const;

export type BackgroundType = (typeof BACKGROUND_TYPES)[number];

export const AVAILABILITY_STATES = ['open', 'busy', 'not_looking'] as const;
